let ide1 = document.querySelector('#button-1')
let ide2 = document.querySelector('#button-2')
let ide3 = document.querySelector('#button-3')
const alert1 = () => {
    alert('Man mener at en midlertidig løsning som kan holde skanserne mode de største meteorer er at man bygger missil tårne og raket siloer og noget forsvar som kan sprænge alle de meteorer der kommer mod månen og mod den potentielle måne base lokalisation. Det der dog gør det til en dårlig løsning på problemet er at meteorerne kommer med meget højere hastigheder mod månen en vi kan sende et missil afsted med og det ville også være meget svært at registrere asteroiderne og meteoritterne inden de kommer for tæt på månen så vi kan reagere i tide til at forsvare os med missiler. Og udover det er det også en meget dyrt eftersom at jeg har taget udgangs punkt i tomahavk missiler og Nasas raket priser hvor et tomahavk missil koster 10 millioner dkk ifølge kilde 2 og en Nasa raket koster 140 millioner dkk ifølge kilde 3 og der kommer udover det også til at være mere rumskrald rundt om månen og det kan blive et stort problem med mere rum skrald og flere små kometer som kan skade raketter som skal til og fra månen. Så derfor er det ikke den bedste ide af de 3 ideer der er men måske en midlertidig i meget pressede sitorationer.')
}
const alert2 = () => {
    alert('Meteoritten er lavet af jern. Meteorit har en radius på 0.5 meter. Det tager 1900 newtons at knække en beton klods på 13.97 cm tykkelse. Meteorittens topfart til max altså 250000 km/t. Med de præmisser på plads kan vi begynde og jeg startede med at finde ud af hvad meteorittens volumen var så man kan beregne vægten af meteoritten. Den vil være helt rund godt nok eftersom at jeg ikke kan sætte præcise beregninger af en meteor med den størrelse eftersom at de er ret specielt formerede. 4/3*π *0.5=2.094395102m^3 efter den udregning går vi videre til næste udregning som er af hvad massen af den her meteor som vi gør ved at gange volumen med densiteten af jern. 2.094395102*7.8=16.3362818 kg/m^3 Og så skal vi bare lige regne vores 250000km/t om til m/s som er 69444.44m/s som jeg brugte en smart omregner side til kilde 6 Og nu hvor vi har vores 2 enheder som vi skal bruge til at beregne hvor mange newtons den meteorit vil ramme med sæter vi vores værdiger in i endnu en formel der heder F(newtons) = m*a  16.3362818*69444.44=1134464 newtons Og nu kan vi begynde på at regne op til den mænge newtons ved at vi ved på forhånede hvor mange newtons det tager at knække en 13.97 cm beton klods kan vi bare tage og se hvor mange gange 1900 går op i det tal vi fik før, og se hvor mange gang vi skal gange det med tykkelsen af den originale beton klods på de 13.97 cm tykkelse 1134464/1900=597.0863158*13.97=8341.295832cm=83.413m Så vi har endelig vores svar vores væg skal være alt i alt 83.5 meter tyk for at kunne overleve og beskytte en base mod en enkelt medium størrelse meteorit. Så ud fra det svar jeg har fundet ud af, tror jeg ikke umildbaret at det er månestøvsmurer der er det rette svar på hvad man skal gøre der er simpelt hen ikke nogen mening i at bygge en 83.5 meter tykke murer for at stoppe en meteor') 
}
const alert3 = () => {
    alert('Den mulighed der lige nu ser mest lovende ud af alle de forskellige muligheder der er for at bygge på månen, så er det at bygge i gamle lava rør som blev dannet under månens tidlige eksistens. Grunden til at det er den mest lovende er fordi at hvis vi kun har et entre punkt som liger i overfladen så behøver vi ikke være bange for at blive ramt eftersom at det er meget usandsynligt hvor vi så også kan nævne at chancerne er ikke så store alligevel for at blive ramt af meteoritter. Men det kan måske godt blive lidt pladsmangel for vi ved trods alt ikke endnu omkring hvor meget plads der er i de her lava rør vi har kun et estimeret tal på omkring 80 - 88 meters dybde og det kan blive lidt trængt med en større base. Men det er den ide som Nasa holdet mener er mest sandsynlig lige nu udefra hvor vores teknologiske standpunkt.')
}

ide1.addEventListener('click',alert1)
ide2.addEventListener('click',alert2)
ide3.addEventListener('click',alert3)

